# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-19 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170419_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minionloadavg',
            name='minionid',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='minionid'),
            preserve_default=False,
        ),
    ]
