# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-20 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170419_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterLoadAvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatetime', models.CharField(blank=True, max_length=30, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('one', models.CharField(blank=True, max_length=30, verbose_name='1 min')),
                ('five', models.CharField(blank=True, max_length=30, verbose_name='5 min')),
                ('fifteen', models.CharField(blank=True, max_length=30, verbose_name='15 min')),
                ('processes', models.CharField(blank=True, max_length=30, verbose_name='\u8fd0\u884c\u8fdb\u7a0b\u6570/\u603b\u8fdb\u7a0b\u6570')),
                ('nowprocesspid', models.CharField(blank=True, max_length=30, verbose_name='\u6700\u8fd1\u8fd0\u884c\u8fdb\u7a0bPID')),
            ],
            options={
                'verbose_name': 'master\u8d1f\u8f7d',
                'verbose_name_plural': 'master\u8d1f\u8f7d',
            },
        ),
        migrations.AlterField(
            model_name='minionloadavg',
            name='nowprocesspid',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u6700\u8fd1\u8fd0\u884c\u8fdb\u7a0bPID'),
        ),
    ]
