# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-20 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170420_0130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterLoadAvg',
            new_name='MasterLoadAvg',
        ),
    ]
