# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-20 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_masterprocessstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinionOnlineNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatetime', models.CharField(blank=True, max_length=30, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('all', models.IntegerField(blank=True, max_length=9999, verbose_name='\u603b\u91cf')),
                ('online', models.IntegerField(blank=True, max_length=9999, verbose_name='\u5728\u7ebf')),
                ('offline', models.IntegerField(blank=True, max_length=9999, verbose_name='\u79bb\u7ebf')),
            ],
            options={
                'verbose_name': 'minion\u5728\u7ebf\u6570\u91cf',
                'verbose_name_plural': 'minion\u5728\u7ebf\u6570\u91cf',
            },
        ),
    ]
