# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-06 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagoryen', models.CharField(blank=True, max_length=30, verbose_name='\u7c7b\u522b\u7b80\u79f0')),
                ('catagorycn', models.CharField(blank=True, max_length=30, verbose_name='\u7c7b\u522b\u5168\u79f0')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b\u5217\u8868',
                'verbose_name_plural': '\u5206\u7c7b\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcen', models.CharField(blank=True, max_length=30, verbose_name='\u673a\u623f\u7b80\u79f0')),
                ('dccn', models.CharField(blank=True, max_length=30, verbose_name='\u673a\u623f\u5168\u79f0')),
            ],
            options={
                'verbose_name': '\u673a\u623f\u5217\u8868',
                'verbose_name_plural': '\u673a\u623f\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Dzhuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='\u7528\u6237\u540d')),
                ('engineer', models.CharField(blank=True, max_length=30, verbose_name='\u7ef4\u62a4\u4eba\u5458')),
            ],
            options={
                'verbose_name': '\u7ef4\u62a4\u4eba\u5458\u5217\u8868',
                'verbose_name_plural': '\u7ef4\u62a4\u4eba\u5458\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=15, verbose_name='IP\u5730\u5740')),
                ('hostname', models.CharField(max_length=30, verbose_name='\u4e3b\u673a\u540d')),
                ('minionid', models.CharField(max_length=60, verbose_name='MinionID')),
                ('nocn', models.CharField(max_length=30, verbose_name='\u8fd0\u8425\u5546\u5168\u79f0')),
                ('catagorycn', models.CharField(blank=True, max_length=30, verbose_name='\u7c7b\u522b')),
                ('pacn', models.CharField(max_length=30, verbose_name='\u5730\u533a\u5168\u79f0')),
                ('dccn', models.CharField(blank=True, max_length=30, verbose_name='\u673a\u623f\u5168\u79f0')),
                ('engineer', models.CharField(blank=True, max_length=30, verbose_name='\u7ef4\u62a4\u4eba\u5458')),
                ('macaddr', models.CharField(blank=True, max_length=20, verbose_name='MAC\u5730\u5740')),
                ('zsourceip', models.CharField(blank=True, max_length=30, verbose_name='\u4e3b\u884c\u60c5\u6e90')),
                ('bsourceip', models.CharField(blank=True, max_length=30, verbose_name='\u5907\u884c\u60c5\u6e90')),
                ('licdate', models.CharField(blank=True, max_length=30, verbose_name='\u6388\u6743\u65e5\u671f')),
                ('licstatus', models.CharField(blank=True, max_length=30, verbose_name='\u6388\u6743\u72b6\u6001')),
                ('idip', models.CharField(blank=True, max_length=15, verbose_name='MinionID\u4e2d\u7684IP\u5730\u5740')),
                ('ipsame', models.CharField(blank=True, max_length=10, verbose_name='IP\u5730\u5740\u4e00\u81f4\u6027')),
                ('remark', models.TextField(blank=True, max_length=200, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ['minionid'],
                'verbose_name': 'Host\u5217\u8868',
                'verbose_name_plural': 'Host\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='NetworkOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noen', models.CharField(blank=True, max_length=30, verbose_name='\u8fd0\u8425\u5546\u7b80\u79f0')),
                ('nocn', models.CharField(blank=True, max_length=30, verbose_name='\u8fd0\u8425\u5546\u5168\u79f0')),
            ],
            options={
                'verbose_name': '\u8fd0\u8425\u5546\u5217\u8868',
                'verbose_name_plural': '\u8fd0\u8425\u5546\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='ProvinceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paen', models.CharField(blank=True, max_length=30, verbose_name='\u7701\u4efd\u5730\u533a\u7b80\u79f0')),
                ('pacn', models.CharField(blank=True, max_length=30, verbose_name='\u7701\u4efd\u5730\u533a\u5168\u79f0')),
            ],
            options={
                'verbose_name': '\u57ce\u5e02\u5217\u8868',
                'verbose_name_plural': '\u57ce\u5e02\u5217\u8868',
            },
        ),
    ]
