# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-11 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccHostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP\u5730\u5740')),
                ('hostname', models.CharField(max_length=30, verbose_name='\u4e3b\u673a\u540d')),
                ('minionid', models.CharField(max_length=60, verbose_name='MinionID')),
                ('osfinger', models.CharField(blank=True, default=b'linux', max_length=60, null=True, verbose_name=b'OS')),
                ('key_tag', models.CharField(choices=[(b'acc', b'Accepted Key')], default=b'acc', max_length=15, verbose_name='salt-key\u72b6\u6001')),
                ('mac_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC\u5730\u5740')),
                ('zsourceip', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e3b\u884c\u60c5\u6e90')),
                ('bsourceip', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5907\u884c\u60c5\u6e90')),
                ('licdate', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6388\u6743\u65e5\u671f')),
                ('licstatus', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6388\u6743\u72b6\u6001')),
                ('idip', models.CharField(blank=True, max_length=15, null=True, verbose_name='MinionID\u4e2d\u7684IP\u5730\u5740')),
                ('ipsame', models.CharField(blank=True, max_length=10, null=True, verbose_name='IP\u5730\u5740\u4e00\u81f4\u6027')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8')),
                ('action', models.CharField(default=b'\xe6\x97\xa0', max_length=1000, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c')),
            ],
            options={
                'ordering': ['minionid'],
                'verbose_name': 'Accepted keys\u5217\u8868',
                'verbose_name_plural': 'Accepted keys\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagoryen', models.CharField(blank=True, max_length=30, verbose_name='\u7c7b\u522b\u7b80\u79f0')),
                ('catagorycn', models.CharField(blank=True, max_length=30, verbose_name='\u7c7b\u522b\u5168\u79f0')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b\u5217\u8868',
                'verbose_name_plural': '\u5206\u7c7b\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcen', models.CharField(blank=True, max_length=30, verbose_name='\u673a\u623f\u7b80\u79f0')),
                ('dccn', models.CharField(blank=True, max_length=30, verbose_name='\u673a\u623f\u5168\u79f0')),
            ],
            options={
                'verbose_name': '\u673a\u623f\u5217\u8868',
                'verbose_name_plural': '\u673a\u623f\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Dzhuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer', models.CharField(blank=True, max_length=30, verbose_name='\u7ef4\u62a4\u4eba\u5458')),
                ('username', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'verbose_name': '\u7ef4\u62a4\u4eba\u5458\u5217\u8868',
                'verbose_name_plural': '\u7ef4\u62a4\u4eba\u5458\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='ErrorHostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP\u5730\u5740')),
                ('hostname', models.CharField(max_length=30, verbose_name='\u4e3b\u673a\u540d')),
                ('minionid', models.CharField(max_length=60, verbose_name='MinionID')),
                ('osfinger', models.CharField(blank=True, default=b'linux', max_length=60, null=True, verbose_name=b'OS')),
                ('key_tag', models.CharField(choices=[(b'error', b'error')], default=b'error', max_length=15, verbose_name='salt-key\u72b6\u6001')),
                ('mac_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC\u5730\u5740')),
                ('zsourceip', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e3b\u884c\u60c5\u6e90')),
                ('bsourceip', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5907\u884c\u60c5\u6e90')),
                ('licdate', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6388\u6743\u65e5\u671f')),
                ('licstatus', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6388\u6743\u72b6\u6001')),
                ('idip', models.CharField(blank=True, max_length=15, null=True, verbose_name='MinionID\u4e2d\u7684IP\u5730\u5740')),
                ('ipsame', models.CharField(blank=True, max_length=10, null=True, verbose_name='IP\u5730\u5740\u4e00\u81f4\u6027')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8')),
                ('action', models.CharField(default=b'\xe6\x97\xa0', max_length=1000, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c')),
                ('catagorycn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.Catagory', verbose_name='\u7c7b\u522b')),
                ('dccn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.DataCenter', verbose_name='\u673a\u623f\u5168\u79f0')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.Dzhuser', verbose_name='\u7ef4\u62a4\u4eba\u5458')),
            ],
            options={
                'ordering': ['minionid'],
                'verbose_name': 'Error keys\u5217\u8868',
                'verbose_name_plural': 'Error keys\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='NetworkOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noen', models.CharField(blank=True, max_length=30, verbose_name='\u8fd0\u8425\u5546\u7b80\u79f0')),
                ('nocn', models.CharField(blank=True, max_length=30, verbose_name='\u8fd0\u8425\u5546\u5168\u79f0')),
            ],
            options={
                'verbose_name': '\u8fd0\u8425\u5546\u5217\u8868',
                'verbose_name_plural': '\u8fd0\u8425\u5546\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='ProvinceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paen', models.CharField(blank=True, max_length=30, verbose_name='\u7701\u4efd\u5730\u533a\u7b80\u79f0')),
                ('pacn', models.CharField(blank=True, max_length=30, verbose_name='\u7701\u4efd\u5730\u533a\u5168\u79f0')),
            ],
            options={
                'verbose_name': '\u57ce\u5e02\u5217\u8868',
                'verbose_name_plural': '\u57ce\u5e02\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='UnAccHostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP\u5730\u5740')),
                ('hostname', models.CharField(max_length=30, verbose_name='\u4e3b\u673a\u540d')),
                ('minionid', models.CharField(max_length=60, verbose_name='MinionID')),
                ('osfinger', models.CharField(blank=True, default=b'linux', max_length=60, null=True, verbose_name=b'OS')),
                ('key_tag', models.CharField(choices=[(b'unacc', b'Unaccepted Key')], default=b'unacc', max_length=15, verbose_name='salt-key\u72b6\u6001')),
                ('mac_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC\u5730\u5740')),
                ('zsourceip', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e3b\u884c\u60c5\u6e90')),
                ('bsourceip', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5907\u884c\u60c5\u6e90')),
                ('licdate', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6388\u6743\u65e5\u671f')),
                ('licstatus', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6388\u6743\u72b6\u6001')),
                ('idip', models.CharField(blank=True, max_length=15, null=True, verbose_name='MinionID\u4e2d\u7684IP\u5730\u5740')),
                ('ipsame', models.CharField(blank=True, max_length=10, null=True, verbose_name='IP\u5730\u5740\u4e00\u81f4\u6027')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8')),
                ('action', models.CharField(default=b'\xe6\x97\xa0', max_length=1000, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c')),
                ('catagorycn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.Catagory', verbose_name='\u7c7b\u522b')),
                ('dccn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.DataCenter', verbose_name='\u673a\u623f\u5168\u79f0')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.Dzhuser', verbose_name='\u7ef4\u62a4\u4eba\u5458')),
                ('nocn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.NetworkOperator', verbose_name='\u8fd0\u8425\u5546\u5168\u79f0')),
                ('pacn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.ProvinceArea', verbose_name='\u5730\u533a\u5168\u79f0')),
            ],
            options={
                'ordering': ['minionid'],
                'verbose_name': 'UnAccepted keys\u5217\u8868',
                'verbose_name_plural': 'UnAccepted keys\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='errorhostlist',
            name='nocn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.NetworkOperator', verbose_name='\u8fd0\u8425\u5546\u5168\u79f0'),
        ),
        migrations.AddField(
            model_name='errorhostlist',
            name='pacn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.ProvinceArea', verbose_name='\u5730\u533a\u5168\u79f0'),
        ),
        migrations.AddField(
            model_name='acchostlist',
            name='catagorycn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.Catagory', verbose_name='\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='acchostlist',
            name='dccn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.DataCenter', verbose_name='\u673a\u623f\u5168\u79f0'),
        ),
        migrations.AddField(
            model_name='acchostlist',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.Dzhuser', verbose_name='\u7ef4\u62a4\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='acchostlist',
            name='nocn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.NetworkOperator', verbose_name='\u8fd0\u8425\u5546\u5168\u79f0'),
        ),
        migrations.AddField(
            model_name='acchostlist',
            name='pacn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.ProvinceArea', verbose_name='\u5730\u533a\u5168\u79f0'),
        ),
    ]
