# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acchostlist',
            name='catagorycn',
        ),
    ]
