# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acchostlist',
            name='bsourceip',
        ),
        migrations.RemoveField(
            model_name='acchostlist',
            name='ipsame',
        ),
        migrations.RemoveField(
            model_name='acchostlist',
            name='licdate',
        ),
        migrations.RemoveField(
            model_name='acchostlist',
            name='licstatus',
        ),
        migrations.RemoveField(
            model_name='acchostlist',
            name='zsourceip',
        ),
        migrations.RemoveField(
            model_name='errorhostlist',
            name='bsourceip',
        ),
        migrations.RemoveField(
            model_name='errorhostlist',
            name='catagorycn',
        ),
        migrations.RemoveField(
            model_name='errorhostlist',
            name='ipsame',
        ),
        migrations.RemoveField(
            model_name='errorhostlist',
            name='licdate',
        ),
        migrations.RemoveField(
            model_name='errorhostlist',
            name='licstatus',
        ),
        migrations.RemoveField(
            model_name='errorhostlist',
            name='zsourceip',
        ),
        migrations.RemoveField(
            model_name='unacchostlist',
            name='bsourceip',
        ),
        migrations.RemoveField(
            model_name='unacchostlist',
            name='catagorycn',
        ),
        migrations.RemoveField(
            model_name='unacchostlist',
            name='ipsame',
        ),
        migrations.RemoveField(
            model_name='unacchostlist',
            name='licdate',
        ),
        migrations.RemoveField(
            model_name='unacchostlist',
            name='licstatus',
        ),
        migrations.RemoveField(
            model_name='unacchostlist',
            name='zsourceip',
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
