# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-08 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unacchostlist',
            name='action',
            field=models.CharField(default=b'<div style="border-top:1px solid #eaeaea;margin-top:30px;">class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">\xe4\xbf\xae\xe6\x94\xb9\xe5\xaf\x86\xe7\xa0\x81</a></div>', max_length=1000, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c'),
        ),
    ]
