# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0002_auto_20170329_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acchostlist',
            name='idip',
        ),
        migrations.RemoveField(
            model_name='errorhostlist',
            name='idip',
        ),
        migrations.RemoveField(
            model_name='unacchostlist',
            name='idip',
        ),
    ]
