# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0002_remove_acchostlist_catagorycn'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinionGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.CharField(blank=True, default=b'', max_length=50, null=True, verbose_name='\u7fa4\u7ec4')),
            ],
            options={
                'verbose_name': 'Minion\u7fa4\u7ec4',
                'verbose_name_plural': 'Minion\u7fa4\u7ec4',
            },
        ),
        migrations.AddField(
            model_name='acchostlist',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='hostlist.MinionGroups', verbose_name='\u7fa4\u7ec4'),
        ),
    ]
