# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0003_auto_20170329_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acchostlist',
            name='ip',
        ),
        migrations.AddField(
            model_name='acchostlist',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'CPU\xe5\x9e\x8b\xe5\x8f\xb7'),
        ),
        migrations.AddField(
            model_name='acchostlist',
            name='cpuarch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'CPU\xe6\x9e\xb6\xe6\x9e\x84'),
        ),
        migrations.AddField(
            model_name='acchostlist',
            name='kernelrelease',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe5\x86\x85\xe6\xa0\xb8\xe7\x89\x88\xe6\x9c\xac'),
        ),
        migrations.AddField(
            model_name='acchostlist',
            name='mem_total',
            field=models.IntegerField(blank=True, max_length=99999, null=True, verbose_name=b'Mem\xe6\x80\xbb\xe9\x87\x8f'),
        ),
        migrations.AddField(
            model_name='acchostlist',
            name='nip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5185\u7f51IP\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='acchostlist',
            name='num_cpus',
            field=models.IntegerField(blank=True, max_length=256, null=True, verbose_name=b'CPU\xe6\x95\xb0\xe9\x87\x8f'),
        ),
        migrations.AddField(
            model_name='acchostlist',
            name='saltversion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='salt\u7248\u672c'),
        ),
        migrations.AddField(
            model_name='acchostlist',
            name='wip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5916\u7f51IP\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='unacchostlist',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'CPU\xe5\x9e\x8b\xe5\x8f\xb7'),
        ),
        migrations.AddField(
            model_name='unacchostlist',
            name='mem_total',
            field=models.IntegerField(blank=True, max_length=99999, null=True, verbose_name=b'Mem\xe6\x80\xbb\xe9\x87\x8f'),
        ),
        migrations.AlterField(
            model_name='acchostlist',
            name='mac_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u673a\u5668\u7801'),
        ),
    ]
