# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0003_auto_20170313_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acchostlist',
            name='groups',
        ),
        migrations.AddField(
            model_name='miniongroups',
            name='minion',
            field=models.ManyToManyField(blank=True, null=True, to='hostlist.AccHostList', verbose_name='\u7fa4\u7ec4'),
        ),
        migrations.AlterField(
            model_name='miniongroups',
            name='Group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7fa4\u7ec4'),
        ),
    ]
