# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-08 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0003_auto_20170308_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unacchostlist',
            name='action',
            field=models.CharField(default=b'\xe6\x97\xa0', max_length=1000, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c'),
        ),
    ]
