# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-06 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0003_auto_20170306_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='pacn',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.ProvinceArea', verbose_name='\u5730\u533a\u5168\u79f0'),
        ),
    ]
