# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-06 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0004_auto_20170306_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostlist',
            name='is_acc',
            field=models.BooleanField(default=False),
        ),
    ]
