# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-08 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0004_auto_20170308_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RejHostList',
        ),
        migrations.CreateModel(
            name='ErrorHostList',
            fields=[
            ],
            options={
                'verbose_name': '\u5f02\u5e38keys\u5217\u8868',
                'proxy': True,
                'verbose_name_plural': '\u5f02\u5e38keys\u5217\u8868',
            },
            bases=('hostlist.unacchostlist',),
        ),
        migrations.AlterField(
            model_name='unacchostlist',
            name='key_tag',
            field=models.CharField(choices=[(b'acc', b'Accepted Key'), (b'unacc', b'Unaccepted Key'), (b'error', b'error')], default=b'unacc', max_length=15, verbose_name='salt-key\u72b6\u6001'),
        ),
    ]
