# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0004_auto_20170329_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acchostlist',
            name='mac_id',
        ),
        migrations.RemoveField(
            model_name='errorhostlist',
            name='mac_id',
        ),
        migrations.RemoveField(
            model_name='unacchostlist',
            name='mac_id',
        ),
    ]
