# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-06 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0005_hostlist_is_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnAccHostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=15, verbose_name='IP\u5730\u5740')),
                ('hostname', models.CharField(max_length=30, verbose_name='\u4e3b\u673a\u540d')),
                ('minionid', models.CharField(max_length=60, verbose_name='MinionID')),
                ('is_acc', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7ed3\u675fminion_id')),
                ('macaddr', models.CharField(blank=True, max_length=20, verbose_name='MAC\u5730\u5740')),
                ('zsourceip', models.CharField(blank=True, max_length=30, verbose_name='\u4e3b\u884c\u60c5\u6e90')),
                ('bsourceip', models.CharField(blank=True, max_length=30, verbose_name='\u5907\u884c\u60c5\u6e90')),
                ('licdate', models.CharField(blank=True, max_length=30, verbose_name='\u6388\u6743\u65e5\u671f')),
                ('licstatus', models.CharField(blank=True, max_length=30, verbose_name='\u6388\u6743\u72b6\u6001')),
                ('idip', models.CharField(blank=True, max_length=15, verbose_name='MinionID\u4e2d\u7684IP\u5730\u5740')),
                ('ipsame', models.CharField(blank=True, max_length=10, verbose_name='IP\u5730\u5740\u4e00\u81f4\u6027')),
                ('remark', models.TextField(blank=True, max_length=200, verbose_name='\u5907\u6ce8')),
                ('catagorycn', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.Catagory', verbose_name='\u7c7b\u522b')),
                ('dccn', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.DataCenter', verbose_name='\u673a\u623f\u5168\u79f0')),
                ('engineer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.Dzhuser', verbose_name='\u7ef4\u62a4\u4eba\u5458')),
                ('nocn', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.NetworkOperator', verbose_name='\u8fd0\u8425\u5546\u5168\u79f0')),
                ('pacn', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.ProvinceArea', verbose_name='\u5730\u533a\u5168\u79f0')),
            ],
            options={
                'ordering': ['minionid'],
                'verbose_name': 'Host\u5217\u8868-\u9a8c\u8bc1salt_id',
                'verbose_name_plural': 'Host\u5217\u8868-\u9a8c\u8bc1salt_id',
            },
        ),
        migrations.RemoveField(
            model_name='hostlist',
            name='catagorycn',
        ),
        migrations.RemoveField(
            model_name='hostlist',
            name='dccn',
        ),
        migrations.RemoveField(
            model_name='hostlist',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='hostlist',
            name='nocn',
        ),
        migrations.RemoveField(
            model_name='hostlist',
            name='pacn',
        ),
        migrations.DeleteModel(
            name='HostList',
        ),
        migrations.CreateModel(
            name='AccHostList',
            fields=[
            ],
            options={
                'verbose_name': 'Host\u5217\u8868-\u672a\u9a8c\u8bc1salt_id',
                'proxy': True,
                'verbose_name_plural': 'Host\u5217\u8868-\u672a\u9a8c\u8bc1salt_id',
            },
            bases=('hostlist.unacchostlist',),
        ),
    ]
