# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-07 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0005_auto_20170329_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acchostlist',
            name='hostname',
            field=models.CharField(max_length=60, verbose_name='\u4e3b\u673a\u540d'),
        ),
    ]
