# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-07 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0006_auto_20170306_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acchostlist',
            options={'verbose_name': '\u672a\u9a8c\u8bc1minion_id\u5217\u8868', 'verbose_name_plural': '\u672a\u9a8c\u8bc1minion_id\u5217\u8868'},
        ),
        migrations.AlterModelOptions(
            name='unacchostlist',
            options={'ordering': ['minionid'], 'verbose_name': '\u5df2\u9a8c\u8bc1minion_id\u5217\u8868', 'verbose_name_plural': 'Host\u5217\u8868-\u9a8c\u8bc1salt_id'},
        ),
        migrations.RenameField(
            model_name='unacchostlist',
            old_name='macaddr',
            new_name='mac_id',
        ),
    ]
