# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-20 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0006_auto_20170407_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acchostlist',
            name='num_cpus',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=b'CPU\xe6\x95\xb0\xe9\x87\x8f'),
        ),
    ]
