# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-08 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0006_unacchostlist_osfinger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unacchostlist',
            name='mac_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC\u5730\u5740'),
        ),
    ]
