# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-09 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0007_auto_20170308_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unacchostlist',
            name='ip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IP\u5730\u5740'),
        ),
    ]
