# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-07 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0008_auto_20170307_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unacchostlist',
            name='bsourceip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5907\u884c\u60c5\u6e90'),
        ),
        migrations.AlterField(
            model_name='unacchostlist',
            name='catagorycn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.Catagory', verbose_name='\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='unacchostlist',
            name='dccn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.DataCenter', verbose_name='\u673a\u623f\u5168\u79f0'),
        ),
        migrations.AlterField(
            model_name='unacchostlist',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.Dzhuser', verbose_name='\u7ef4\u62a4\u4eba\u5458'),
        ),
        migrations.AlterField(
            model_name='unacchostlist',
            name='idip',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='MinionID\u4e2d\u7684IP\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='unacchostlist',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IP\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='unacchostlist',
            name='ipsame',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='IP\u5730\u5740\u4e00\u81f4\u6027'),
        ),
        migrations.AlterField(
            model_name='unacchostlist',
            name='licdate',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6388\u6743\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='unacchostlist',
            name='licstatus',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6388\u6743\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='unacchostlist',
            name='mac_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MAC\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='unacchostlist',
            name='pacn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.ProvinceArea', verbose_name='\u5730\u533a\u5168\u79f0'),
        ),
        migrations.AlterField(
            model_name='unacchostlist',
            name='remark',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='unacchostlist',
            name='zsourceip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e3b\u884c\u60c5\u6e90'),
        ),
    ]
