# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-23 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowtime', models.DateTimeField(blank=True, null=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('user_operate', models.CharField(blank=True, max_length=100, verbose_name='\u7528\u6237\u64cd\u4f5c')),
                ('simple_tgt', models.CharField(blank=True, max_length=30, verbose_name='\u76ee\u6807\u7b80\u8ff0')),
                ('jid', models.CharField(blank=True, max_length=255, verbose_name='jid')),
                ('username', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u64cd\u4f5c\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u64cd\u4f5c\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(blank=True, max_length=255, verbose_name='jid')),
                ('tgt_total', models.CharField(blank=True, max_length=10, verbose_name='\u76ee\u6807\u603b\u6570')),
                ('tgt_ret', models.CharField(blank=True, max_length=10, verbose_name='\u6709\u8fd4\u56de\u7ed3\u679c\u7684\u4e3b\u673a\u6570\u91cf')),
                ('tgt_succ', models.CharField(blank=True, max_length=10, verbose_name='\u6210\u529f\u7684\u4e3b\u673a\u6570\u91cf')),
                ('tgt_fail', models.CharField(blank=True, max_length=10, verbose_name='\u5931\u8d25\u7684\u4e3b\u673a\u6570\u91cf')),
                ('tgt_unret', models.CharField(blank=True, max_length=10, verbose_name='\u672a\u8fd4\u56de\u7ed3\u679c\u7684\u4e3b\u673a\u6570\u91cf')),
                ('tgt_unret_list', models.TextField(blank=True, verbose_name='\u672a\u8fd4\u56de\u7ed3\u679c\u7684\u4e3b\u673a\u5217\u8868')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u64cd\u4f5c\u8fd4\u56de\u7ed3\u679c',
                'verbose_name_plural': '\u7528\u6237\u64cd\u4f5c\u8fd4\u56de\u7ed3\u679c',
            },
        ),
    ]
