# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-17 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnRecord',
        ),
        migrations.RemoveField(
            model_name='operaterecord',
            name='jid',
        ),
        migrations.RemoveField(
            model_name='operaterecord',
            name='simple_tgt',
        ),
        migrations.AlterField(
            model_name='operaterecord',
            name='user_operate',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u64cd\u4f5c\u8bb0\u5f55'),
        ),
    ]
