# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-17 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20170417_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaterecord',
            name='user_operate',
            field=models.CharField(blank=True, max_length=9999, verbose_name='\u64cd\u4f5c\u8bb0\u5f55'),
        ),
    ]
