# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_uploadfiles_filepath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='filepath',
            new_name='filesource',
        ),
    ]
