# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_auto_20170403_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='filesource',
        ),
    ]
