# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-28 13:54
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='memo',
            field=DjangoUeditor.models.UEditorField(default=b'', verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default=b'', verbose_name='\u5408\u540c\u8be6\u7ec6'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo',
            field=DjangoUeditor.models.UEditorField(default=b'', verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='memo',
            field=DjangoUeditor.models.UEditorField(default=b'', verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='memo',
            field=DjangoUeditor.models.UEditorField(default=b'', verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default=b'', verbose_name='\u4e8b\u4ef6\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='memo',
            field=DjangoUeditor.models.UEditorField(default=b'', verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='memo',
            field=DjangoUeditor.models.UEditorField(default=b'', verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='device_detail',
            field=DjangoUeditor.models.UEditorField(default=b'', verbose_name='\u8bbe\u5907\u8be6\u60c5\u914d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='data',
            field=DjangoUeditor.models.UEditorField(default=b'', verbose_name='\u8d44\u4ea7\u6570\u636e'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='memo',
            field=DjangoUeditor.models.UEditorField(default=b'', verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='raidadaptor',
            name='memo',
            field=DjangoUeditor.models.UEditorField(default=b'', verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='memo',
            field=DjangoUeditor.models.UEditorField(default=b'', verbose_name='\u5907\u6ce8'),
        ),
    ]
