# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-03 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20170228_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='asset_type',
            field=models.CharField(blank=True, choices=[(b'server', '\u670d\u52a1\u5668'), (b'switch', '\u4ea4\u6362\u673a'), (b'router', '\u8def\u7531\u5668'), (b'firewall', '\u9632\u706b\u5899'), (b'storage', '\u5b58\u50a8\u8bbe\u5907'), (b'NLB', 'NetScaler'), (b'wireless', '\u65e0\u7ebfAP'), (b'software', '\u8f6f\u4ef6\u8d44\u4ea7'), (b'others', '\u5176\u5b83\u7c7b')], max_length=64, null=True, verbose_name='\u670d\u52a1\u5668\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='cpu_core_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU\u6838\u5fc3\u6570'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='cpu_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU\u4e2a\u6570'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='manufactory',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5236\u9020\u5546'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='os_distribution',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u53d1\u884c\u7cfb\u7edf\u7248\u672c'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='os_release',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7248\u672c'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='os_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='ram_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
