# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-03 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20170303_1508'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together=set([]),
        ),
    ]
