# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-03 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20170303_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
        migrations.AlterField(
            model_name='raidadaptor',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together=set([('asset', 'slot')]),
        ),
    ]
