# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-03 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20170303_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='manufactory_support_num',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u5236\u9020\u5546\u652f\u6301\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufactory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5236\u9020\u5546'),
        ),
        migrations.DeleteModel(
            name='Manufactory',
        ),
    ]
