# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-03 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20170303_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='all_ram_size',
            field=models.IntegerField(default=0, verbose_name='\u5185\u5b58\u603b\u91cf'),
        ),
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together=set([('asset', 'slot')]),
        ),
    ]
