# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-04 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20170303_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '\u6807\u7b7e', 'verbose_name_plural': '\u6807\u7b7e'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[(b'server', '\u670d\u52a1\u5668'), (b'networkdevice', '\u7f51\u7edc\u8bbe\u5907'), (b'storagedevice', '\u5b58\u50a8\u8bbe\u5907'), (b'securitydevice', '\u5b89\u5168\u8bbe\u5907'), (b'securitydevice', '\u673a\u623f\u8bbe\u5907'), (b'software', '\u8f6f\u4ef6\u8d44\u4ea7')], default=b'server', max_length=64, verbose_name='\u670d\u52a1\u5668\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.SmallIntegerField(choices=[(0, b'\xe5\x9c\xa8\xe7\xba\xbf'), (1, b'\xe5\xb7\xb2\xe4\xb8\x8b\xe7\xba\xbf'), (2, b'\xe6\x9c\xaa\xe7\x9f\xa5'), (3, b'\xe6\x95\x85\xe9\x9a\x9c'), (4, b'\xe5\xa4\x87\xe7\x94\xa8')], default=0, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='asset.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='detail',
            field=models.TextField(verbose_name='\u4e8b\u4ef6\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
