# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-04 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20170304_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlog',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventLog',
        ),
    ]
