# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-04 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_emaliverifyrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmaliVerifyRecord',
        ),
    ]
