# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-01 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IvModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logname', models.CharField(max_length=255, verbose_name='log\u540d\u79f0')),
                ('iv', models.IntegerField(verbose_name='IV')),
                ('timestamps', models.CharField(max_length=255, verbose_name='\u7edf\u8ba1\u65f6\u95f4\u6233')),
            ],
        ),
        migrations.CreateModel(
            name='PvModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logname', models.CharField(max_length=255, verbose_name='log\u540d\u79f0')),
                ('pv', models.IntegerField(verbose_name='PV')),
                ('timestamps', models.CharField(max_length=255, verbose_name='\u7edf\u8ba1\u65f6\u95f4\u6233')),
            ],
        ),
        migrations.CreateModel(
            name='UvModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logname', models.CharField(max_length=255, verbose_name='log\u540d\u79f0')),
                ('uv', models.IntegerField(verbose_name='UV')),
                ('timestamps', models.CharField(max_length=255, verbose_name='\u7edf\u8ba1\u65f6\u95f4\u6233')),
            ],
        ),
        migrations.AddField(
            model_name='weblog',
            name='timestamps',
            field=models.CharField(default=1, max_length=255, verbose_name='\u7edf\u8ba1\u65f6\u95f4\u6233'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weblog',
            name='logname',
            field=models.CharField(max_length=255, verbose_name='log\u540d\u79f0'),
        ),
    ]
