# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-30 11:28
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u670d\u52a1\u540d\u79f0')),
                ('envtag', models.CharField(choices=[('pro', 'Product Enviroment,'), ('dev', 'Development Enviroment,')], default='dev', max_length=20, verbose_name='\u73af\u5883\u72b6\u6001')),
                ('sls', DjangoUeditor.models.UEditorField(default='', verbose_name='sls\u914d\u7f6e')),
            ],
        ),
    ]
