# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-06 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jids',
            fields=[
                ('jid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('load', models.TextField()),
            ],
            options={
                'db_table': 'jids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaltReturns',
            fields=[
                ('useless', models.AutoField(primary_key=True, serialize=False)),
                ('fun', models.CharField(max_length=50)),
                ('jid', models.CharField(max_length=255)),
                ('return_field', models.TextField(db_column='return')),
                ('id', models.CharField(max_length=255)),
                ('success', models.CharField(max_length=10)),
                ('full_ret', models.TextField()),
                ('alter_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'salt_returns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommonOperate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slsfile', models.CharField(blank=True, max_length=255, verbose_name='sls\u6587\u4ef6')),
                ('module', models.CharField(blank=True, max_length=30, verbose_name='\u6a21\u5757\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slsfile', models.CharField(blank=True, max_length=255, verbose_name='sls\u6587\u4ef6')),
                ('module', models.CharField(blank=True, max_length=30, verbose_name='\u6a21\u5757\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='DangerCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50, unique=True, verbose_name='\u547d\u4ee4')),
                ('status', models.CharField(max_length=20, verbose_name='\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='DeployModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slsfile', models.CharField(blank=True, max_length=255, verbose_name='sls\u6587\u4ef6')),
                ('module', models.CharField(blank=True, max_length=30, verbose_name='\u6a21\u5757\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='ModulesLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=30, verbose_name='\u6a21\u5757\u540d\u79f0')),
                ('status', models.CharField(blank=True, max_length=30, verbose_name='\u4f7f\u7528\u72b6\u6001')),
                ('user', models.CharField(blank=True, max_length=30, verbose_name='\u7528\u6237')),
            ],
        ),
    ]
