# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-07 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonoperate',
            options={'verbose_name': '\u7a0b\u5e8fsls\u7ef4\u62a4', 'verbose_name_plural': '\u7a0b\u5e8fsls\u7ef4\u62a4'},
        ),
        migrations.AlterModelOptions(
            name='configupdate',
            options={'verbose_name': '\u7a0b\u5e8fsls\u66f4\u65b0', 'verbose_name_plural': '\u7a0b\u5e8fsls\u66f4\u65b0'},
        ),
        migrations.AlterModelOptions(
            name='dangercommand',
            options={'verbose_name': '\u5371\u9669\u547d\u4ee4', 'verbose_name_plural': '\u5371\u9669\u547d\u4ee4'},
        ),
        migrations.AlterModelOptions(
            name='deploymodules',
            options={'verbose_name': '\u7a0b\u5e8fsls\u90e8\u7f72', 'verbose_name_plural': '\u7a0b\u5e8fsls\u90e8\u7f72'},
        ),
        migrations.AlterModelOptions(
            name='moduleslock',
            options={'verbose_name': '\u6a21\u5757\u4f7f\u7528\u72b6\u6001', 'verbose_name_plural': '\u6a21\u5757\u4f7f\u7528\u72b6\u6001'},
        ),
    ]
