# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-30 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0005_auto_20170329_1614'),
        ('saltstack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '\u670d\u52a1(.sls)', 'verbose_name_plural': '\u670d\u52a1(.sls)'},
        ),
        migrations.AddField(
            model_name='service',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='hostlist.MinionGroups', verbose_name='\u7fa4\u7ec4'),
        ),
        migrations.AddField(
            model_name='service',
            name='minions',
            field=models.ManyToManyField(blank=True, null=True, to='hostlist.AccHostList', verbose_name='\u4e3b\u673a'),
        ),
        migrations.AlterField(
            model_name='service',
            name='envtag',
            field=models.CharField(choices=[('pro', '\u751f\u4ea7'), ('dev', '\u5f00\u53d1')], default='dev', max_length=20, verbose_name='\u73af\u5883\u72b6\u6001'),
        ),
    ]
