# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-30 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0002_auto_20170330_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sls',
            field=models.TextField(blank=True, max_length=99999, null=True, verbose_name='sls\u914d\u7f6e\u6587\u4ef6'),
        ),
    ]
