# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-12 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0001_initial'),
        ('saltstack', '0003_auto_20170312_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinionGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u7fa4\u7ec4')),
                ('minion', models.ManyToManyField(blank=True, default='', null=True, to='hostlist.AccHostList', verbose_name='Minion')),
            ],
            options={
                'verbose_name': 'Minion\u7fa4\u7ec4',
                'verbose_name_plural': 'Minion\u7fa4\u7ec4',
            },
        ),
    ]
