# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-05 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0007_remove_uploadfiles_groups'),
        ('saltstack', '0003_auto_20170330_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='file',
            field=models.ManyToManyField(to='fileupload.UploadFiles', verbose_name='\u914d\u7f6e\u9644\u4ef6'),
        ),
    ]
