# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-06 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0004_service_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, to='fileupload.UploadFiles', verbose_name='\u914d\u7f6e\u9644\u4ef6'),
        ),
    ]
