# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0004_miniongroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniongroups',
            name='minion',
            field=models.ManyToManyField(blank=True, null=True, to='hostlist.AccHostList', verbose_name='Minion'),
        ),
    ]
