# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0005_auto_20170312_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniongroups',
            name='minion',
        ),
        migrations.DeleteModel(
            name='MinionGroups',
        ),
    ]
