# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-09 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0006_auto_20170406_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='\u670d\u52a1\u540d\u79f0'),
        ),
    ]
